services:
  docs:
    image: gab_turism_local_docs
    container_name: gab_turism_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./gab_turism:/app/gab_turism:z
    ports:
      - '9000:9000'
    command: /start-docs
